### ISSUE TITLE
Ignoring subfolders doesn't seem to work on locations defined in run_on

### ISSUE THREAD

**Issue by tormi** [wunderio/code-quality#51]
Ref: https://wunder.slack.com/archives/C5B9YGQSE/p1597407241011400

> How can I define working ignore_patterns for folders which are subfolders of ones which are defined in run_on? This doesn’t seem to work:

```
    ecs:
      run_on: ['web/modules/custom', 'web/themes/custom', 'web/sites']
      ignore_patterns:
        - '/web/sites/default/files/'
```

<img width="990" alt="Screenshot 2020-08-14 at 15 41 58 (1)" src="https://user-images.githubusercontent.com/146800/90474152-4f64b780-e12d-11ea-9b5b-7fb0599813ed.png">

cc: @guncha25
