### ISSUE TITLE
Re-add back ecs and code complexity for D10

### ISSUE THREAD

**Issue by hkirsman** [wunderio/code-quality#72]
These were removed here https://github.com/wunderio/code-quality/pull/71/files because we were not able to upgrade ECS on D9.

**Comment by hkirsman** [comment]
Probably this is needed:

        "wunderio/ecs-drupal": "^1.0",
        "symplify/coding-standard": "^11.3",


Or at least let's start from latest 11.3.

Then we also need to change that requirement here:

https://github.com/wunderio/ecs-drupal/blob/master/composer.json

Related issue at https://github.com/wunderio/ecs-drupal/issues/2

**Comment by hkirsman** [comment]
Cognitive complexity used to need these lines
```

services:
    -
        class: Symplify\CodingStandard\CognitiveComplexity\Rules\FunctionLikeCognitiveComplexityRule
        tags: [phpstan.rules.rule]
        arguments:
            maxMethodCognitiveComplexity: 16
    -
        class: Symplify\CodingStandard\CognitiveComplexity\Rules\ClassLikeCognitiveComplexityRule
        tags: [phpstan.rules.rule]
        arguments:
            maxClassCognitiveComplexity: 50
```

It's yelling:
`  Service (Symplify\CodingStandard\CognitiveComplexity\Rules\FunctionLikeCognitiveComplexityRule::__construct()): Class 'Symplify\CodingStandard\CognitiveComplexity\Rules\FunctionLikeCognitiveComplexityRule' not found.  
`

But seems they don't exist anymore and this might be the reason. New package is needed.

https://github.com/symplify/symplify/pull/4515
